server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: catalogue
        uri: http://localhost:9082/
        predicates:
        - Path=/catalogue/**
      - id: shoppingcart
        uri: http://localhost:9083/
        predicates:
        - Path=/shoppingcart/**
      - id: userinfo
        uri: http://localhost:9081/
        predicates:
        - Path=/userinfo/**
        
okta:
    oauth2:
        clientId: 0oac075nvDAYJ5YhX4x6
        clientSecret: <<ClientSecret>>
        issuer: https://dev-243143.okta.com/oauth2/default        